# Generated by Django 4.2.6 on 2023-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_post_dislikers_post_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislike_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
