# Generated by Django 4.2.6 on 2023-10-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_post_dislike_count_post_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_post",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="base.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="dislike_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
