# Generated by Django 4.2.6 on 2023-10-31 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0004_alter_comment_author_alter_comment_parent_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="enrolled_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
